// src/components/common/ConfettiOverlay.jsx
/**
 * ConfettiOverlay — Full-screen confetti burst for celebrations.
 * Particles are generated by GameEngine.makeConfettiBurst().
 *
 * Props:
 *   active  – boolean (show/hide)
 *   count   – number of particles (default 70)
 */
import React, { memo, useMemo } from 'react';
import GameEngine from '../../services/GameEngine';

const CONFETTI_CSS = `
  @keyframes confettiFall {
    0%   { transform: translateY(-10vh) rotate(0deg)   scaleX(1); opacity: 1; }
    70%  { opacity: 1; }
    100% { transform: translateY(105vh) rotate(720deg) scaleX(0.6); opacity: 0; }
  }
`;

const ConfettiOverlay = memo(({ active, count = 70 }) => {
  const particles = useMemo(
    () => (active ? GameEngine.makeConfettiBurst(count) : []),
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [active],
  );

  if (!active) return null;

  return (
    <>
      <style>{CONFETTI_CSS}</style>
      <div style={{
        position: 'fixed', inset: 0,
        pointerEvents: 'none',
        zIndex: 999,
        overflow: 'hidden',
      }}>
        {particles.map((p) => (
          <div
            key={p.id}
            style={{
              position:        'absolute',
              top:             '-12px',
              left:            `${p.x}%`,
              width:           p.size,
              height:          p.size * 0.55,
              background:      p.color,
              borderRadius:    2,
              animation:       `confettiFall ${p.duration}s ease-in ${p.delay}s both`,
              transform:       `rotate(${p.rotation}deg)`,
            }}
          />
        ))}
      </div>
    </>
  );
});

export default ConfettiOverlay;
